#!/bin/sh
#
# 40autorandr: Change autorandr profile on thaw/resume
exec > /var/log/autorandr.log 2>&1

AUTORANDR="autorandr -c"

detect_display()
{
	for X in /tmp/.X11-unix/X*; do
		D="${X##/tmp/.X11-unix/X}"
		user=`w -h | awk -vD="$D" '$3 ~ ":"D"(\\.[0-9])?$" {print $1}'`
		logger "user $user"
		if [ x"$user" != x"" ]; then
			export DISPLAY=":$D"
			/bin/su -c "${AUTORANDR}" "$user"
		fi
	done
}

case "$1" in
	thaw|resume)
		detect_display
		;;
esac
